// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	User *User  `json:"user"`
	UUID string `json:"uuid"`
}

type LoginResponse struct {
	UUID string `json:"uuid"`
}

type RegisteredResponse struct {
	Status string `json:"status"`
}

type User struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
