// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisteredResponse struct {
	Status string `json:"status"`
}

type User struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
